"""users table

Revision ID: 1db57db9fd6a
Revises: 2fb89c0a6a18
Create Date: 2021-03-28 17:20:17.464484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1db57db9fd6a'
down_revision = '2fb89c0a6a18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=True)
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###
